mozilla/ssh_scan

bin/ssh_scan
lib/ssh_scan/policy.rb
lib/ssh_scan/scan_engine.rb
policies/mozilla_intermediate.yml
policies/mozilla_modern.yml

First stab at addressing #9 in an effort to make policy management more portable and easier to edit.

Move SSH compliance policies to JSON format

---

ssh_scan.gemspec

When running ssh_scan from gem install the policies were not being shipped with the gem, resulting in the following error...
$ ssh_scan 192.168.10.186
/Users/jclaudius/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/psych.rb:464:in `initialize': No such file or directory @ rb_sysopen - /Users/jclaudius/.rvm/gems/ruby-2.2.3/gems/ssh_scan-0.0.3/policies/mozilla_modern.yml (Errno::ENOENT)
from /Users/jclaudius/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/psych.rb:464:in `open'
from /Users/jclaudius/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/psych.rb:464:in `load_file'
from /Users/jclaudius/.rvm/gems/ruby-2.2.3/gems/ssh_scan-0.0.3/lib/ssh_scan/policy.rb:16:in `from_file'
from /Users/jclaudius/.rvm/gems/ruby-2.2.3/gems/ssh_scan-0.0.3/bin/ssh_scan:22:in `<top (required)>'
from …

Add policies to gem

---

lib/ssh_scan/os/ubuntu.rb

Discovered a bug when running against scanme.nmap.org.  Found a typo in the Ubuntu OS fingerprinter.
$ ./bin/ssh_scan -t scanme.nmap.org
{
"ssh_scan_version": "0.0.8",
"hostname": "scanme.nmap.org",
"ip": "45.33.32.156",
"port": 22,
"server_banner": "SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.7",
"ssh_version": 2.0,
"os": "ubuntu",
"os_cpe": "o:canonical:freebsd",
"ssh_lib": "openssh",
"ssh_lib_cpe": "a:openssh:openssh",
"key_algorithms": [
"curve25519-sha256@libssh.org",
"ecdh-sha2-nistp256",
"ecdh-sha2-nistp384",
"ecdh-sha2-nistp521",
"diffie-hellman-group-exchange-sha256",
"diffie-hellman-group-exchange-sha1",
"diffie-hellman-group14-sha1",
"diffie-hellman-group1-sha1"
],
"server_host_key_algorithms": [
"ssh-rsa",
"ssh-dss",
"ecdsa-sha2-nistp256",
"ssh-ed25519"
], …

Fix OS fingerprinting bug

---

lib/ssh_scan/policy_manager.rb

Extra space in list of entries to be added was present if someone copy pastes the list in sshd_config file in hope of getting the right configuration this results in a ssh server launch failure.
Similar space in list of stuff to removed doesn't matters as they will anyways be required to be removed manually.
Hope this helps

removed extra space which was resulting is server panic

---

lib/ssh_scan/scan_engine.rb

I thought this was fixed in #67, but apparently I never removed the original offending code.

Fix host key bug

---

.travis.yml
Dockerfile

@jvehent here's an attempt to see if we can fix this up.  It's likely we might not even need a ruby env provided by travis to build the docker image and it might be able to be it's own thing.

Try out some docker changes

---

.travis.yml
Dockerfile

If this works, we could add automated publication of the container in the mozilla org on dockerhub.

Build docker container in travisci

---

README.md
bin/ssh_scan
lib/ssh_scan/scan_engine.rb
lib/ssh_scan/target_parser.rb
spec/ssh_scan/integration.sh
spec/ssh_scan/target_parser_rspec.rb
ssh_scan.gemspec

Fixes https://github.com/mozilla/ssh_scan/issues/99
This PR adds support for custom ports in input file. For example,
```bash
192.168.1.1,192.168.1.1:2222,192.168.1.2
```
- Added support for using output file as input for rescans  (https://github.com/mozilla/ssh_scan/issues/101).
Now we can use 
```bash
ssh_scan -O output.json -o rescan_output.json
```
How about this? @claudijd

Add support for custom ports in input file and support rescans

---

lib/ssh_scan/policy.rb
lib/ssh_scan/policy_manager.rb
spec/ssh_scan/policy_manager_spec.rb

To add a whitelist of auth_methods, we just need to add the below sample block to the `policy.yml` file:
```yml
auth_methods:
- publickey
- password
```
If no whitelist of auth_methods is provided, it assumes all `auth_methods` are valid.

Added auth_methods as a policy control. Fixes #139

---

policies/mozilla_intermediate.yml
policies/mozilla_modern.yml

Because #42 happened, adding publickey requirements to both intermediate and modern policy defaults.  Many thanks to @yashmehrotra for making that happen!
I also ran a test case on this here, looks good....
[
{
"ssh_scan_version": "0.0.11",
"ip": "192.168.0.34",
"port": "22",
"server_banner": "SSH-2.0-OpenSSH_7.2p2 Debian-5",
"ssh_version": 2.0,
"os": "debian",
"os_cpe": "o:debian:debian",
"ssh_lib": "openssh",
"ssh_lib_cpe": "a:openssh:openssh:7.2p2",
"cookie": "06d4d24ad7cdeebe2a38e682adede6f8",
"key_algorithms": [
"curve25519-sha256@libssh.org",
"ecdh-sha2-nistp256",
"ecdh-sha2-nistp384",
"ecdh-sha2-nistp521",
"diffie-hellman-group-exchange-sha256",
"diffie-hellman-group14-sha1"
],
"server_host_key_algorithms": [
"ssh-rsa",
"rsa-sha2-512",
"rsa-sha2-256",
"ecdsa-sha2-nistp256", …

Add publickey to auth_methods default policies

---

lib/ssh_scan/policy_manager.rb
lib/ssh_scan/scan_engine.rb

In cases when net-ssh bonks at trying to actually negotiate a session and is disconnected, let's still provide compliance results for information we do have.

Provide compliance results with partial success

---

spec/ssh_scan/banner/banner_spec.rb
spec/ssh_scan/banner/generic_spec.rb
spec/ssh_scan/banner/helper.rb
spec/ssh_scan/banner/mixed_spec.rb
spec/ssh_scan/banner/os/ubuntu_spec.rb
spec/ssh_scan/banner/ssh_lib/dropbear_spec.rb

For #168 
This way, anyone who wants to write a spec test for an OS (say Debian) can make a file in spec/ssh_scan as os/debian_spec.rb
```
require 'rspec'
require_relative '../helper'
describe ...
context ...
expectations = {
.. fingerprints ..
}
checkFingerprints(expectations)
end
end
```
I hope this make it easier. Please do suggest ways to improve this structure of tests, thanks!

break fingerprint specs into their own files

---

lib/ssh_scan/policy.rb
lib/ssh_scan/policy_manager.rb
policies/mozilla_intermediate.yml
policies/mozilla_modern.yml
spec/ssh_scan/policy_manager_spec.rb

We just need to add `ssh_version: <minimum>` to the `yml` file.

Added SSH version as a policy control. Fixes #154

---

lib/ssh_scan/client.rb

The bug here is that banner was not being output as a string, it was output as a Klass.to_s equivalent, which was not ideal, but it was caught when trying to stuff into mongo

Fix banner class bug

---

lib/ssh_scan/policy_manager.rb

@claudijd Fixed #183 , stupid mistake, my bad.

Fix condition check for SSH policy control. Fixes #183.

---

lib/ssh_scan/crypto.rb
lib/ssh_scan/scan_engine.rb
spec/ssh_scan/crypto_spec.rb

For #84.
I had some doubts on how to generate the ECDSA fingerprints, so didn't push that change in this PR.

take out host key fingerprinting from scan_engine

---

.gitignore
bin/ssh_scan
lib/ssh_scan/fingerprint_database.rb
lib/ssh_scan/scan_engine.rb
spec/ssh_scan/fingerprint_database_spec.rb
ssh_scan.gemspec

To reproduce this behavior, it requires a little hacking if you don't have an example target...
You're need to scan a host to generate a local fingerprint DB stub
./bin/ssh_scan -t 192.168.10.99
At this time, you shouldn't have any duplicates in your results.  To insert a duplicate into the db you can do this...
sqlite3 fingerprints.db
insert into fingerprints values ('8a:92:84:06:ca:08:64:85:28:a0:36:0f:82:f3:dc:75:01:fc:01:82:35:e8:93:28:9d:e3:aa:b0:33:59:61:16', '192.168.10.100');
Make sure to use a fingerprint string from the original scan.
Once this is added, you can now rescan and get the following host key duplicate decorators...
"duplicate_host_key_ips": [
"192.168.10.100"
],
This new information added to scans will let us know if we ever come across a host that is sharing keys …

Add persistent fingerprint DB capability

---

spec/ssh_scan/enforce_signed_commits.rb

For #236.
The Travis CI build should fail since last changes to enforce_signed_commits.rb were unsigned.

update enforce logic, shift checks

---

bin/ssh_scan_api
bin/ssh_scan_api_example_config.yml
lib/ssh_scan/api.rb
lib/ssh_scan/authenticator.rb
lib/ssh_scan/constants.rb
lib/ssh_scan/version.rb
lib/ssh_scan/worker.rb
spec/ssh_scan/api_spec.rb
spec/ssh_scan/version_spec.rb

Adds a crude authentication layer to the ssh_scan_api
Fixes #262

Add authentication to ssh_scan_api

---

.gitignore
lib/ssh_scan/api.rb
lib/ssh_scan/api_db.rb
lib/ssh_scan/worker.rb

For https://github.com/mozilla/ssh_scan/issues/266 . 
`/api/v1/scan/results?uuid=uuid_string` returns the scan with the specified uuid.
`/api/v1/work/results/worker_id/uuid` returns the scan with specified worker_id and uuid.
`/api/v1/scan/results/delete/worker_id/uuid` deletes the scan with specified worked_id and uuid.
`/api/v1/scan/results/delete/all` deletes all the rows in the table.
@claudijd @pwnbus @gdestuynder review?

Added data store for API results

---

bin/ssh_scan

should solve the port before target issue (#278), although reorder_args! assumes that args to be ordered are 2 element args (key/value).

reorder arguments before processing

---

bin/ssh_scan_api_example_config.yml
lib/ssh_scan/api.rb
nginx/example.conf

SSL termination on webrick/thin was proving to be annoying, so I switched the deployment model over nginx so developers don't even need to worry about it and provided an example of the nginx config in git so it's transparent how it's all setup.

Switch to nginx for SSL/TLS termination

---

bin/ssh_scan_worker_example_config.yml
lib/ssh_scan/worker.rb

Make the worker a little more flexible to allow HTTP/HTTPS comms, this sets the default to HTTP to be helpful to develop but allows you some tunables you might want as you work toward a production setup.

Fix up worker to allow HTTP/HTTPS options

---

bin/ssh_scan
lib/ssh_scan/api.rb
lib/ssh_scan/database.rb
lib/ssh_scan/database/mongo.rb
lib/ssh_scan/database/sqlite.rb
spec/ssh_scan/api_spec.rb
spec/ssh_scan/database/mongodb_spec.rb
spec/ssh_scan/database/sqlite_spec.rb
spec/ssh_scan/database_spec.rb

Provides a caching feature in the API retrieving pre-existing scan results when present.
I am still working on it but opening this PR so that everyone can see where it is headed and suggest improvements.
This PR is separate from but is based on changes from PR #291, so it contains changes from earlier PR mixed with this too.
This addresses Issue #296.

API caching feature

---

config/api/config.yml
config/worker/config.yml
lib/ssh_scan/worker.rb
ssh_scan.gemspec

FYI @rishabhs95 @royalharsh 
Moves auth token into the config, so we don't have to set ENV vars.
Also, adds a conditional so that no-auth support still functions and resets expectations to the most usable setup (eg. no auth)

Fix worker authentication bug

---

.gitmodules
.travis.yml
examples/github.com.json
lib/ssh_scan/crypto.rb
lib/ssh_scan/scan_engine.rb
ssh_scan.gemspec

Fix #343 
This adds the known_bad fingerprints to the respective RSA/DSA grouping, like so making direct use of known bad host keys from https://github.com/rapid7/ssh-badkeys.  For testing, I just copied over my DSA host key and dropped it in the ssh-badkeys host folder with a .key extension to get it to load and test the new feature.
"fingerprints": {
"rsa": {
"known_bad": "false",
"md5": "46:7e:dd:ff:c9:14:d3:da:50:72:83:1a:77:73:5d:8f",
"sha1": "ef:3f:94:fa:ad:e6:1d:b9:24:a4:30:79:4a:13:2e:74:48:71:a1:7e",
"sha256": "49:5d:53:ce:d5:bf:e8:e9:b1:99:95:1a:20:96:a3:53:08:26:90:48:cc:ea:cf:57:7d:00:43:bc:ed:c0:ee:c0"
},
"dsa": {
"known_bad": "true",
"md5": "5d:80:de:85:af:fb:fc:ac:44:0f:b7:50:08:09:e7:d6",
"sha1": "00:45:70:88:a5:2b:57:91:1a:0a:45:05:1b:fe:7a:51:15:0c:5c:3e",
"sha256": …

Add ssh-badkey detection

---

spec/ssh_scan/string_ext_spec.rb

* This test fails on a machine that does not 
resolve the ipv6 localhost address (eg. a machine
where /etc/hosts does not contain `::1 localhost`

Updates test for localhost resolution

---

bin/ssh_scan
lib/ssh_scan/version.rb

temporarily disabling update checks
Reasons:
- people with SSL configuration issues complain that it's an unnecessary blocker to perform an ssh_scan (and they are right)
- it actually slows down scans (~3sec before, ~1sec after) and I think that is significant in terms of perf
Maybe the above reasons are enough to make it not temporary but more long lasting, but I want to get something out to them sooner than later so they can get on with their scanning.

Bump for 0.0.20 release

---

README.md

This is more of a cross-linking effort to help shuttle people to the right project to meet their needs, whether it be command-line or API driven scans.

Add call out to ssh_scan_api project

---

.travis.yml

Reverting this change as it had the unintended consequence of blocking docker push actions indefinately forcing people to be stuck on a specific build even when they were trying to update from the docker deployment strategy.

Restore travis docker pushes from branches

---

ssh_scan.gemspec

I ran into some problems with a deployment about netaddr not installing, I happened to notice I was rolling with netaddr 1.5.1 and 2.x was released today, so I think that's somehow related.  I may go and report that upstream once I get my thing fixed.

Bind to a specific version of netaddr

---

lib/ssh_scan/scan_engine.rb

ssh_keyscan is behaving weirdly when a port is passed to it as an
argument. By weird what I mean is instead of sending to output stdout it is
redirected to stderr. This is a temporary fix and it needs more
investigation why is that the case.
@claudijd  @jumanjiman

fix #432: Fix the regression present in v0.33

---

.travis.yml
lib/ssh_scan/version.rb
ssh_scan.gemspec

Fixes an unbound dependency upper bound which can cause exceptions at net-ssh 5.x and adds more CI integration test coverage

Bump CI ruby versions

---

Dockerfile
spec/ssh_scan/integration.sh

This PR proposes switching to an Alpine-based image base `ruby:alpine` instead of using the default Debian-based `ruby` build. The switch can allow the general users to enjoy a smaller Docker image.
On my testing box, the image shrank from 913MB to 93.1MB.

Use alpine build for Docker

---

lib/ssh_scan/public_key.rb
lib/ssh_scan/scan_engine.rb
spec/public_key_spec.rb

Fixes #486
Example output changes:
"keys": {
"ecdsa-sha2-nistp256": {
"raw": "ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBC4gXA5naQtjcKu90NJ7A4jQ1UgxYGdnndJyr4PSZJ59qJUzkoH3VgdTlseXbIZHwO4k2gNcFpaMq5gqVRobAwU=",
"length": 520,
"fingerprints": {
"md5": "be:04:32:74:c6:63:fa:24:c3:c6:78:c2:cd:d2:3e:f4",
"sha1": "00:67:e3:4d:78:2f:65:94:87:bf:54:5a:1e:92:af:67:0b:8d:b5:2c",
"sha256": "EZe8ZoSwAzDOLR45H2PZ1aGGfnt59ZLrL5bwnjQwTUI="
}
},
"rsa": {
"raw": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCl/BNLUxR49+3AKqhf6sWKrh8XXzqXV00bEPFtcJFWxyRqC5pPWo9zRRiS2jitIcqljIQVohEEZHt48vZaA1hniVfe/FmrFzuCOuQOIP2fuRgLSNHu+lWVScsHoX/MuYXEIxj6aW7UpFn4lD01mvPtazXFO/tJ+LRs49YBP7UvL1smIS2xoyuH7kZDN17QG08YwbIB2fApMl8rXH+2Rpj5hlv+7rcZ1dqCGtmXmvsv8fKGYd7BxRy0s/d7EY4e/DeDxA1qTNV9BrBTNn6jAKIedT …

Add support for ecdsa and ed25519 keys

---

Dockerfile

This PR resolves #510 by working around the non-apk-provided ruby 2.7.0 from `alpine:ruby` using environment variables.
I did the following:
- Redefined `GEM_HOME` from upstream to be accurate
- Removed `gem install bundler` as it is provided upstream in `/usr/local/bin`
- Added `build-base` to `apk del` to be symmetric with the temporary `apk add`
There are no automated tests but I have manually verified that the following results in JSON output:
$ docker build -t ssh_scan .
$ docker run -it ssh_scan /app/bin/ssh_scan -t sshscan.rubidus.com
[...]
A better way to fix this may be to submit an upstream PR to the maintainers of `alpine:ruby` so that they can set the correct `GEM_*` environment variables according to the source-built version of ruby they choose to use.
For now, however, I …

Fix 510: tweak Dockerfile to work around upstream environment issue with Ruby 2.7.0

---

build_and_deploy_to_dockerhub.sh

Fail the TravisCI build if there is an error in the script _build_and_deploy_to_dockerhub.sh_.
**What I expected:**
```
To install the missing version, run `gem install bundler:1.17.3`
from /usr/local/lib/ruby/2.7.0/rubygems.rb:296:in `activate_bin_path'
from /usr/local/bin/bundle:23:in `<main>'
The command '/bin/sh -c apk --update add --virtual build-dependencies build-base &&     bundle install &&     apk del build-dependencies build-base &&     rm -rf /var/cache/apk/*' returned a non-zero code: 1
The command "./build_and_deploy_to_dockerhub.sh" exited with 1.
Done. Your build exited with 1.
```
**What happened:**
Although the pipeline / job status reports success since the script is ignoring the errors.
```
The command '/bin/sh -c apk --update add --virtual build-dependencies …
```

Fix Docker Hub build and deploy script to fail the job 

---

Dockerfile
README.md

I made a small tweak to the Dockerfile to make running ssh_scan from a container easier. Now instead of
```
docker run -it mozilla/ssh_scan /app/bin/ssh_scan -t sshscan.rubidus.com
```
it's just
```
docker run -it mozilla/ssh_scan -t sshscan.rubidus.com
```

Dockerfile improvements
