ssh_scan.rb
=> Fix port bug

ssh_scan.rb
Make sure the class types are consistent between default port and user supplied port.
=> Fix alternating port class types

examples/192.168.1.1.json, lib/ssh_scan/policy_manager.rb
=> Add missing matches

README.md, bin/ssh_scan, lib/ssh_scan/version.rb
=> Improve option parsing

Gemfile, README.md, bin/ssh_scan, lib/ssh_scan/client.rb, lib/ssh_scan/scan_engine.rb, lib/string_ext.rb
=> Add hostname targeting

lib/ssh_scan/policy_manager.rb
=> Fix compression bug

lib/ssh_scan/client.rb
Adding version information to output to help with troubleshooting/transparency
=> Add ssh_scan version to output

README.md, bin/ssh_scan, lib/ssh_scan/version.rb
=> Add unit-test/CI exit-code capability

.travis.yml, README.md, bin/ssh_scan, examples/localhost_v6.json
- IPv6 updates to help and README.md
- Adds v6 example of using ssh_scan
=> Add more explicit support for IPv6

lib/ssh_scan/banner.rb, lib/ssh_scan/client.rb, lib/ssh_scan/constants.rb, lib/ssh_scan/os.rb, lib/ssh_scan/os/centos.rb, lib/ssh_scan/os/debian.rb, lib/ssh_scan/os/freebsd.rb, lib/ssh_scan/os/ubuntu.rb, lib/ssh_scan/os/unknown.rb, lib/ssh_scan/ssh_lib.rb, lib/ssh_scan/ssh_lib/libssh.rb, lib/ssh_scan/ssh_lib/openssh.rb, lib/ssh_scan/ssh_lib/unknown.rb, spec/ssh_scan/banner_spec.rb, spec/ssh_scan/client_spec.rb, spec/ssh_scan/constants_spec.rb
Adds the following...
- Banner object class (to better handle the server banner)
- Banner#os_guess (to detect server OS by SSH banner)
- Banner#ssh_lib_guess (to detect server ssh library using SSH banner)
- A bunch of specs to verify the above items work as expected
=> Add fingerprinting stub

lib/ssh_scan/scan_engine.rb
I have added auth enumerations using net-ssh. Have a look at the patch and any comments? @claudijd
=> Fixes #28 Add support for auth method enumeration

spec/ssh_scan/version_spec.rb
Add a little more sanity to SSHScan versioning
=> Add another unit-test for versions

lib/ssh_scan/scan_engine.rb
=> Fix bug in host key class verification

bin/ssh_scan, lib/ssh_scan/scan_engine.rb
@claudijd  Syntax looks like this ./bin/ssh_scan -t github.com,128.237.153.145
=> Multi IP Support comma seperated

README.md
Minor grammar and formatting fixes. Cleanups.
=> README.md: Minor grammar and formatting fixes.

lib/ssh_scan/scan_engine.rb
=> Fix net-ssh custom port bug

bin/ssh_scan
=> Reading IPs via File

lib/ssh_scan/scan_engine.rb
It was probably a usability mistake to make this a hard failure, making it a warning for now until I can find time to add alternative host-key support.
=> Host-key support type work around

examples/github.com.json, lib/ssh_scan/policy.rb, lib/ssh_scan/policy_manager.rb, policies/mozilla_intermediate.yml, policies/mozilla_modern.yml, spec/ssh_scan/policy_spec.rb
=> Add policy references

bin/ssh_scan, lib/ssh_scan.rb, lib/ssh_scan/target_parser.rb, spec/ssh_scan/target_parser_rspec.rb
@claudijd Updated Pull Requested
=> Custom Parser

bin/ssh_scan, lib/ssh_scan/client.rb, lib/ssh_scan/error.rb, lib/ssh_scan/error/closed_connection.rb, lib/ssh_scan/error/connect_timeout.rb, lib/ssh_scan/scan_engine.rb, spec/ssh_scan/client_spec.rb, ssh_scan.gemspec
With respect to #64. 
Please indicate things that should be changed in the PR, if any. Thanks!
=> add timeout options

bin/ssh_scan, lib/ssh_scan/client.rb, lib/ssh_scan/error.rb, lib/ssh_scan/error/connection_refused.rb, lib/ssh_scan/error/disconnected.rb, lib/ssh_scan/scan_engine.rb
- Uses a finite limit on thread pools (default 5)
- Adds some exception handling (now that we can scan more than a host at a time)
- Changes default timeout from 3sec to 2 sec
=> Improve exception handling logic

lib/ssh_scan/client.rb, lib/ssh_scan/constants.rb, lib/ssh_scan/protocol.rb, lib/string_ext.rb, spec/ssh_scan/constants_spec.rb, spec/ssh_scan/protocol_spec.rb
=> Make SSHScan::KeyExchangeInit buildable from scratch

lib/ssh_scan/banner.rb, lib/ssh_scan/os/ubuntu.rb, spec/ssh_scan/banner_spec.rb
For #51 (Ubuntu)
Scraped the ChangeLog from Ubuntu's OpenSSH repo on Launchpad, some versions may repeat. (https://launchpad.net/ubuntu/+source/openssh/+changelog)
I hope this is what you intended? If you want, I can add the scraping script (also in ruby) here, for reference.
Thanks!
=> add ubuntu banners

ssh_scan.gemspec
@jinankjain has been super active on this project and I feel like it's only fair to list him now as an official author of this project.
=> Add Jinak Jain as an author

lib/ssh_scan/version.rb
=> Bump version for 0.0.11 release

spec/ssh_scan/policy_manager_spec.rb
unit tests for policy manager.
@claudijd Please review I have added the assert statements.
=> Fixed #127

lib/ssh_scan/banner.rb, lib/ssh_scan/os/centos.rb, lib/ssh_scan/os/cisco.rb, lib/ssh_scan/os/debian.rb, lib/ssh_scan/os/freebsd.rb, lib/ssh_scan/os/redhat.rb, lib/ssh_scan/os/ubuntu.rb, lib/ssh_scan/os/unknown.rb, lib/ssh_scan/os/windows.rb, lib/ssh_scan/ssh_lib/ciscossh.rb, lib/ssh_scan/ssh_lib/libssh.rb, lib/ssh_scan/ssh_lib/unknown.rb, spec/ssh_scan/banner_spec.rb
make it easier to write specs for fingerprint verification
=> Simplify fingerprint harness

bin/ssh_scan
@claudijd @royalharsh I had fixed that error in #125
=> Fixes #130

lib/ssh_scan/client.rb
@claudijd There were different errors for mac and linux.
=> Fixes #161

README.md, bin/ssh_scan
@claudijd Added Logging Facility. Fixes #159
=> Added the standard Logger

bin/ssh_scan, lib/ssh_scan/scan_engine.rb
=> Add logger by default

lib/ssh_scan/client.rb
=> Fixed #170

README.md
=> Added gitter chat room

bin/ssh_scan, lib/ssh_scan/scan_engine.rb, lib/ssh_scan/target_parser.rb, spec/ssh_scan/target_parser_spec.rb
@claudijd  @agaurav77  Fixed that port issue by overwriting ports with what is specified in -p
=> Fixed port issue

lib/ssh_scan/scan_engine.rb
=> Add start/end/duration values to scan output

lib/ssh_scan/client.rb
@claudijd This might help in fixing #186
=> Fixes #186

lib/ssh_scan/scan_engine.rb
=> Use null host key verifier

lib/ssh_scan/client.rb
Fixes #191 
This improves some of the exception handling logic when kex_init's break down.
Doesn't consider re-tries, but we may consider adding re-tries in the future if this is really a common occurrence.
=> Fix exception handling bug #191 in client #get_kex_result

lib/ssh_scan/scan_engine.rb
=> Make compliance a decorator

lib/ssh_scan/os/ubuntu.rb, spec/ssh_scan/banner/os/ubuntu_spec.rb
=> Add ubuntu fingerprints to specs

bin/ssh_scan, lib/ssh_scan.rb, lib/ssh_scan/update.rb
=> Add gem update warnings/status

lib/ssh_scan/os/ubuntu.rb, spec/ssh_scan/banner/helper.rb, spec/ssh_scan/banner/os/ubuntu_spec.rb
=> report unknown when ubuntu version cannot be identified

bin/ssh_scan, lib/ssh_scan/update.rb
=> make update checking an opt-out feature

_layouts/default.html, _layouts/post.html, index.html
=> fix css/js on gh-pages

_layouts/default.html, _layouts/page.html, _layouts/post.html, feed.xml, index.html
=> fix baseurl errors

index.html
=> fix posts bug

spec/ssh_scan/string_ext_spec.rb
=> specs for string_ext.rb

.gitignore, lib/ssh_scan/api.rb, spec/ssh_scan/api_spec.rb
=> heartbeat route for api #238

.travis.yml, spec/ssh_scan/enforce_signed_commits.rb
For #236 
Still have to add pwnbus and kang's GPG keys.
=> enforce signed commits on master

README.md
This is a verification step to ensure the signed commits test is working as expected.
=> Unsigned test commit

scripts/Ubuntu.rb
=> add ubuntu openssh scraping script

spec/ssh_scan/enforce_signed_commits.rb
=> update enforce logic

README.md
Last commit is unsigned, travis should fail.
=> test commit, signed

.gitignore, Rakefile
=> correct tar path for win32 systems

spec/ssh_scan/enforce_signed_commits.rb
Additional changes for enforce_signed_commits.rb, #236.
=> fixes for enforce_signed_commits.rb

.gitignore, bin/ssh_scan_api, lib/ssh_scan/api.rb, spec/ssh_scan/api_spec.rb, ssh_scan.gemspec
Add support for https, #233  
I and @agaurav77 are still working on more suitable tests.
=> add https support 

.gitignore, .travis.yml, bin/ssh_scan, bin/ssh_scan_api, bin/ssh_scan_worker, lib/ssh_scan.rb, lib/ssh_scan/api.rb, lib/ssh_scan/job_queue.rb, lib/ssh_scan/scan_engine.rb, lib/ssh_scan/worker.rb, spec/ssh_scan/api_spec.rb, spec/ssh_scan/integration.sh
An addendum to #259 to help suggest the direction of abstracting the worker class.  Debugging threads within threads was just a pain to deal with.
/cc @rishabhs95 please check these changes out. I cut out some code (namely the fingerprint db) and abstracted the worker class into it's own process and added the API endpoints necessary for the worker to remotely interact with the API.  It's still very much a work in progress, but I though this would help get you unstuck on #259
=> Rishabhs95 job queueing suggestions

bin/ssh_scan_worker, lib/ssh_scan/worker.rb
=> Clean up worker class interfaces

bin/ssh_scan_api, bin/ssh_scan_api_example_config.yml, bin/ssh_scan_worker_example_config.yml, lib/ssh_scan.rb, lib/ssh_scan/api.rb
Move worker and api to yaml based configs
=> Moar config improvements

lib/ssh_scan/scan_engine.rb
=> Fix compliance policy file reference bug

bin/ssh_scan, spec/ssh_scan/integration.sh
=> Fix #279 - verbosity bug

lib/ssh_scan/api.rb
Few changes to ssl_opts in api.rb.
=> Add ssl_opts changes to api.rb

lib/ssh_scan/policy_manager.rb
=> fix nit in policy_manager

bin/ssh_scan_worker_example_config.yml, lib/ssh_scan/scan_engine.rb, lib/ssh_scan/worker.rb
An attempt to do more clean informative logging on the worker node.
=> Fix up worker logs

lib/ssh_scan/api.rb, spec/ssh_scan/api_spec.rb
Adds exceptional Sinatra configs for unit tests
Issue #294.
=> Restore API unit tests

Gemfile, README.md, spec/spec_helper.rb
=> Revert "Add coveralls"

config/api/config.yml, lib/ssh_scan/authenticator.rb, lib/ssh_scan/worker.rb
I think this may not be the best solution, but just posting this as it works. :)
Issue #328.
I think we can get a better solution with the suggestions from #321.
=> probable repair for auth

lib/ssh_scan/stats.rb, spec/ssh_scan/stats_spec.rb
@royalharsh @rishabhs95 what do you think about something like this for cleaning up #322 ?
=> Suggestion for stats interface

lib/ssh_scan/api.rb
=> Allow localhost workers/users to bypass auth

lib/ssh_scan/api.rb, lib/ssh_scan/stats.rb, spec/ssh_scan/stats_spec.rb
Solves: https://github.com/mozilla/ssh_scan/issues/309
- `api/v1/stats`
=> Stats interface

lib/ssh_scan/scan_engine.rb, lib/string_ext.rb
=> Add PTR lookup on IP-only target

lib/ssh_scan/crypto.rb
* Also top-scopes `Base64` requests
Closes #346
=> Adds base64 to requirements for fingerprint check

lib/ssh_scan/scan_engine.rb
=> Fix duplicate fingerprint bug

bin/ssh_scan, lib/ssh_scan/fingerprint_database.rb, spec/ssh_scan/fingerprint_database_spec.rb, ssh_scan.gemspec
=> Replace SQLite with YAML::Store

lib/ssh_scan/banner.rb, lib/ssh_scan/constants.rb, lib/ssh_scan/crypto.rb, lib/ssh_scan/error/closed_connection.rb, lib/ssh_scan/error/connect_timeout.rb, lib/ssh_scan/error/connection_refused.rb, lib/ssh_scan/error/disconnected.rb, lib/ssh_scan/error/no_banner.rb, lib/ssh_scan/error/no_kex_response.rb, lib/ssh_scan/fingerprint_database.rb, lib/ssh_scan/os/raspbian.rb, lib/ssh_scan/os/ubuntu.rb, lib/ssh_scan/policy.rb, lib/ssh_scan/policy_manager.rb, lib/ssh_scan/protocol.rb, lib/ssh_scan/scan_engine.rb, lib/ssh_scan/target_parser.rb, lib/ssh_scan/update.rb, ssh_scan.gemspec
Should be an okay-ish start for documentation.
#319
=> add yard, initial documentation comments

config/policies/mozilla_intermediate.yml, config/policies/mozilla_modern.yml, lib/ssh_scan/policy.rb, lib/ssh_scan/policy_manager.rb, spec/ssh_scan/policy_manager_spec.rb
Fixes https://github.com/mozilla/ssh_scan_api/issues/34
=> Only report on items in the policy

lib/ssh_scan.rb, lib/ssh_scan/grader.rb, lib/ssh_scan/scan_engine.rb, spec/ssh_scan/grader_spec.rb
=> Add grader

lib/ssh_scan/client.rb
Fixes https://github.com/mozilla/ssh_scan_api/issues/51
=> Add exception handling for unresolvable IP

.travis.yml
=> Restrict docker runs to master only

bin/ssh_scan, lib/ssh_scan.rb, lib/ssh_scan/banner.rb, lib/ssh_scan/client.rb, lib/ssh_scan/grader.rb, lib/ssh_scan/policy_manager.rb, lib/ssh_scan/result.rb, lib/ssh_scan/scan_engine.rb, spec/ssh_scan/grader_spec.rb, spec/ssh_scan/policy_manager_spec.rb, spec/ssh_scan/result_spec.rb
Working toward fixing https://github.com/mozilla/ssh_scan/issues/377
=> Refactor how we handle results into a well-formed class (with specs!)

.travis.yml
=> Integration tests for docker

lib/ssh_scan/client.rb
=> Provide exception handling for banner grabbing

lib/ssh_scan/result.rb, spec/ssh_scan/result_spec.rb
=> Add unit-tests for potential results bug

lib/ssh_scan/client.rb, lib/ssh_scan/scan_engine.rb
- Add better exception handling for Net::SSH
- Make client observe timeout restrictions imposed on it
=> Various bug fixes

.travis.yml, lib/ssh_scan/scan_engine.rb
=> Move to open3 for ssh-keyscan

lib/ssh_scan/result.rb, spec/ssh_scan/grader_spec.rb, spec/ssh_scan/result_spec.rb
This was causing grades to not populate
=> Bug fix for grade

lib/ssh_scan/public_key.rb, lib/ssh_scan/result.rb, lib/ssh_scan/scan_engine.rb, lib/ssh_scan/ssh_fp.rb, lib/string_ext.rb, spec/public_key_spec.rb, spec/ssh_scan/result_spec.rb, spec/ssh_scan/ssh_fp_spec.rb
Fixes #489, which was requested in #476
=> Add sshfp support

lib/ssh_scan/result.rb, spec/ssh_scan/result_spec.rb
=> Add jstangroome fix

ssh_scan.gemspec
use latest net-ssh https://github.com/net-ssh/net-ssh/blob/master/CHANGES.txt#L10
=> use latest stable net-ssh 5.2.0

.travis.yml, Dockerfile
Attempt to update the travis and Docker rubies.
=> Update rubies in travis and Docker

README.md
=> Remove deadline to achiinema
